///////////////////////////////////////////////////////////
//  EstadoIntervencion.cs
//  Implementation of the Class EstadoIntervencion
//  Generated by Enterprise Architect
//  Created on:      13-oct.-2019 22:31:16
//  Original author: CYRO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CU71
{
    public abstract class EstadoIntervencion
    {

        private DateTime fecha;

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean abortar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean cancelar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean convocar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        public Boolean esAbortada()
        {

            return false;
        }

        public Boolean esCancelada()
        {

            return false;
        }

        public Boolean esConvocada()
        {

            return false;
        }

        public Boolean esEnCurso()
        {

            return false;
        }

        public Boolean esFinalizada()
        {

            return false;
        }

        public Boolean esFirmada()
        {

            return false;
        }

        public Boolean esPendiente()
        {

            return false;
        }

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean finalizar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean firmar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        public delegate DateTime getFecha();

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>

        public Boolean iniciar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }

        /// 
        /// <param name="fecha"></param>
        /// <param name="this"></param>
        public Boolean programar(DateTime fecha, Intervencion inter)
        {

            throw new NotImplementedException();
        }
    }//end EstadoIntervencion
}
