///////////////////////////////////////////////////////////
//  EstadoFinalizada.cs
//  Implementation of the Class EstadoFinalizada
//  Generated by Enterprise Architect
//  Created on:      13-oct.-2019 22:31:16
//  Original author: CYRO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CU71
{
    public class EstadoFinalizada : EstadoIntervencion
    {
        private DateTime fecha;

        public EstadoFinalizada(DateTime fecha)
        {
            this.fecha = fecha;
        }
    }
}
