///////////////////////////////////////////////////////////
//  GestorFinalizacionIntervencion.cs
//  Implementation of the Class GestorFinalizacionIntervencion
//  Generated by Enterprise Architect
//  Created on:      13-oct.-2019 22:31:16
//  Original author: CYRO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CU71
{
    public class GestorFinalizacionIntervencion
    {

        private Bombero bomberos;
        private String datosIngresadosDotacion;
        private Intervencion[] intervenciones;
        private Intervencion intervencionSeleccionada;
        private Sesion sesionActual;

        public GestorFinalizacionIntervencion()
        {

        }

        ~GestorFinalizacionIntervencion()
        {

        }

        public void buscarIntervencionesEnCurso()
        {

            foreach (Intervencion inter in intervenciones)
            {
                // Duda de como manejar esto, porque tengo que buscar las intervenciones para
                // mandarle datos a la interfaz visual para que el usuario seleccione una
                if (inter.esEnCurso())
                {

                }
            }
        }

        public void confirmarFinalizacionIntervencion()
        {

        }

        public void finalizarIntervencion()
        {

        }

        public void finCU()
        {

        }

        public void mostrarDotacionesFinalizables()
        {

        }

        public DateTime obtenerFechaHoraActual()
        {
            return System.DateTime.Now;
        }

        public Usuario obtenerUsuarioSesionActual()
        {

            return null;
        }

        public void ordenarIntervencionesPorFecha()
        {

        }

        public void registrarFinalizacionIntervencion()
        {
            DateTime fechaActual = this.obtenerFechaHoraActual();
            intervencionSeleccionada.finalizar(fechaActual);
        }

        public void seleccionarIntervencionAFinalizar()
        {

        }

        public void validarFechaHoraLlegadaDotaciones()
        {

        }

        public void validarKmAlRegresarDotaciones()
        {

        }

    }//end GestorFinalizacionIntervencion
}
