///////////////////////////////////////////////////////////
//  Intervencion.cs
//  Implementation of the Class Intervencion
//  Generated by Enterprise Architect
//  Created on:      13-oct.-2019 22:41:27
//  Original author: CYRO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CU71
{
    public class Intervencion
    {

        private String domicilioReportado;
        private EstadoIntervencion[] estados;
        private String nombreApellidoInformante;
        private String resumenSiniestroInformante;
        private String resumenTrabajoEfectuado;
        private String telefonoContacto;
        public Dotacion dotacion;
        public Convocatoria convocatoria;
        public TipoSiniestro tipoSiniestro;
        public Material materialesUtilizados;
        public HistorialIntervencion historial;
        public Gravedad gravedad;
        public Bombero encargado;

        public void abortar()
        {

        }

        /// 
        /// <param name="estado"></param>
        public void añadirEstado(EstadoIntervencion estado)
        {

        }

        public void cancelar()
        {

        }

        public void contarDotaciones()
        {

        }

        public void convocar()
        {

        }

        public Boolean esEnCurso()
        {

            throw new NotImplementedException();
        }

        public Boolean esFinalizada()
        {

            throw new NotImplementedException();
        }

        public Boolean esTuGravedad()
        {

            throw new NotImplementedException();
        }

        public Boolean esTuTipoSiniestro()
        {

            throw new NotImplementedException();
        }

        public Boolean finalizacionDentroDePeriodo()
        {

            throw new NotImplementedException();
        }

        /// 
        /// <param name="fechaActual"></param>
        public void finalizar(DateTime fechaActual)
        {
            this.getEstadoActual().finalizar(fechaActual, this);
        }

        public void firmar()
        {

        }

        public String getDomicilioReportado()
        {

            return "";
        }

        public EstadoIntervencion getEstadoActual()
        {

            throw new NotImplementedException();
        }

        public DateTime getFechaHoraSolicitud()
        {

            throw new NotImplementedException();
        }

        public Gravedad getGravedad()
        {

            throw new NotImplementedException();
        }

        public String getResumenSiniestro()
        {

            return "";
        }

        public String getResumenTrabajo()
        {

            return "";
        }

        public TipoSiniestro getTipoSiniestro()
        {

            throw new NotImplementedException();
        }

        public void iniciar()
        {

        }

        public String mostrarDatosDotaciones()
        {

            return "";
        }
        public Bombero[] obtenerBomberos()
        {

            throw new NotImplementedException();
        }

        public String obtenerDatos()
        {

            return "";
        }

        public String obtenerDatosDeEncargado()
        {

            return "";
        }

        public EstadoIntervencion obtenerEstadoActual()
        {
            EstadoIntervencion estadoActual;
            foreach (EstadoIntervencion estado in estados)
            {

            }
            return estadoActual;
        }

        public DateTime obtenerTiempoEnCurso()
        {

            throw new NotImplementedException();
        }

        public void programar()
        {

        }

    }
}
