///////////////////////////////////////////////////////////
//  IEstrategiaTiempo.cs
//  Implementation of the Interface IEstrategiaTiempo
//  Generated by Enterprise Architect
//  Created on:      16-oct.-2019 22:40:24
//  Original author: CYRO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CU94
{
	public interface IEstrategiaTiempo  {

		string calcularTiempo(Intervecion[] intervenciones);

		void crear();

		boolean esActiva();
	}//end IEstrategiaTiempo	
}

